language: node_js
node_js:
- node
- 10
- 8
after_success:
- npm run coverage
- npm run build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key:
    secure: McF4iwQRUZ74XD+iE10cpetpCIVJXMmRlAuI1aq+UOMJUfjO/jC1Ma0a1lsLRRgBO2rt7alsILb38zgiDCtGDXBJchRvMTJfU8Cb3XozBhLQLgK+ohe/pORDLm4mA2tay8mmV/2JsJWs7NVGPICenuahdCENakX0EkI5Md55j0wLEv74cqFJQeQhzaesRGIa6EUrDMdxxB+Klyer8q9UAlus3NkFS+AM0AcsYEzfQMFgxCtfsU7sciGlX3uk6mYryg7BktEipjQy9IEvrtNLx/k02tofsNvCxkoGu9BXH1ThV+ZW5VSJ71jWzBQyL/ro16mWf6c/C5uQw32zg4XVGzjTHQm52TsWcZFP612Frtkf5Nn+/Zddv0D1can+uTxKoH/4iOkDRDJ++V234f15hSOFmAbDvW61yr9ZZQtcDquWo+KYgu+jQHfZOSABSMw3EOZzcmQwpmHK8t/ws0xZP5OwpdjOE3lg0hI7p9lsqdmrVGHkJeLXdpAwBa/2klbifON+bu3sF3yiTvAJqjh7jXVaXvbakGkzeQF3l0q9FFCmRmuA4bPETGXc5QMxepnqtEplutJMymMpaofHJoi5orzfubH4kM+9xpDLeErPVcJLXSUulyG/ygrX2zjlD5EFxlFhQspCoRpMj7xr9mFK5053WzsdRbO4P+6n9eHQb70=
  on:
    tags: true
    repo: up9cloud/graphql-tools-type-uuid
    branch: master
